In [10]:
import torch

In [11]:
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])

# Basic math — element-wise, just like NumPy

In [12]:
print(a + b)       # tensor([5., 7., 9.])
print(a * b)       # tensor([ 4., 10., 18.])
print(a ** 2)      # tensor([1., 4., 9.])

tensor([5., 7., 9.])
tensor([ 4., 10., 18.])
tensor([1., 4., 9.])


# Scalar operations also work

In [13]:
print(a * 10)      # tensor([10., 20., 30.])
print(a + 100)     # tensor([101., 102., 103.])

tensor([10., 20., 30.])
tensor([101., 102., 103.])


In [14]:
x = torch.tensor([1.0, 2.0, 3.0, 4.0, 5.0, 6.0])  # shape: (6,)

# Reshape into a 2×3 matrix

In [16]:
x_2d = x.reshape(2, 3)
print(x_2d)
print(x_2d.shape)   # torch.Size([2, 3])

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])


# Reshape into a 2×3 matrix

In [17]:
x_3d = x.reshape(3, 2)
print(x_3d.shape)   # torch.Size([3, 2])

torch.Size([3, 2])


# Use -1 to let PyTorch figure out one dimension automatically

In [20]:
x_auto = x.reshape(-1, 2)   # "I want 2 columns, you figure out the rows"
print(x_auto.shape)          # torch.Size([3, 2])

torch.Size([3, 2])


## In classical ML: y = X @ w  (feature matrix times weights)
## In deep learning: exact same thing, just with tensors

In [21]:
X = torch.tensor([[1.0, 2.0],
                  [3.0, 4.0]])   # shape: (2, 2)

W = torch.tensor([[0.5],
                  [0.5]])        # shape: (2, 1) — think of this as weights

# Matrix multiply — two ways to write it, same result

In [22]:
out = torch.matmul(X, W)
print(out)

tensor([[1.5000],
        [3.5000]])


In [23]:
out = X @ W          # cleaner shorthand, use this
print(out)

tensor([[1.5000],
        [3.5000]])


# --- Indexing and slicing — identical to NumPy ---

In [24]:
x = torch.tensor([[1.0, 2.0, 3.0],
                  [4.0, 5.0, 6.0]])

print(x[0])        # first row  → tensor([1., 2., 3.])
print(x[:, 1])     # all rows, second column → tensor([2., 5.])
print(x[1, 2])     # row 1, col 2 → tensor(6.)

tensor([1., 2., 3.])
tensor([2., 5.])
tensor(6.)


# --- Converting between NumPy and PyTorch ---

In [25]:
import numpy as np

In [26]:
arr = np.array([1.0, 2.0, 3.0])

# NumPy → Tensor
t = torch.from_numpy(arr)
print(t)    # tensor([1., 2., 3.], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)


In [27]:
# Tensor → NumPy
back = t.numpy()
print(back)  # [1. 2. 3.]

[1. 2. 3.]
