In [2]:
import torch

In [3]:
# A normal tensor — no tracking
x = torch.tensor([2.0])
print(x)

# A tensor PyTorch will track
x = torch.tensor([2.0], requires_grad=True)
print(x)

tensor([2.])
tensor([2.], requires_grad=True)


#### Think of 'w' as a single weight in a neural network <br> requires_grad=True tells PyTorch: "track everything done to this"


In [4]:
w = torch.tensor([3.0], requires_grad=True)
w

tensor([3.], requires_grad=True)

#### A simple computation — like a loss function <br> loss = w^2  →  at w=3, loss = 9

In [5]:
loss = w ** 2
print(loss)   # tensor([9.], grad_fn=<PowBackward0>)
#                                   ↑
#              Notice: PyTorch already recorded the operation!

tensor([9.], grad_fn=<PowBackward0>)


#### Now ask PyTorch: "what is d(loss)/d(w)?"

In [6]:
loss.backward()

#### The gradient is stored in w.grad

In [7]:
print(w.grad)   # tensor([6.])

tensor([6.])


# More Realistic Example
#### Two weights — like two parameters in a small model

In [8]:
w1 = torch.tensor([2.0], requires_grad=True)
w2 = torch.tensor([3.0], requires_grad=True)

#### A slightly more complex loss <br> loss = w1^2 + w2^3

In [9]:
loss = w1 ** 2 + w2 ** 3

In [10]:
loss.backward()

#### Gradients computed simultaneously for both

In [12]:
print(w1.grad)   # tensor([4.])  ← d/dw1 of w1² = 2*w1 = 4
print(w2.grad)   # tensor([27.]) ← d/dw2 of w2³ = 3*w2² = 27

tensor([4.])
tensor([27.])


#### PyTorch accumulates gradients by default. So if you call .backward() twice, the gradients add up — which is almost never what you want:

In [13]:
w = torch.tensor([3.0], requires_grad=True)

# First backward
loss = w ** 2
loss.backward()
print(w.grad)   # tensor([6.])  ✅ correct

tensor([6.])


In [14]:
# Second backward WITHOUT zeroing first
loss = w ** 2
loss.backward()
print(w.grad)   # tensor([12.]) ❌ wrong! It added 6 to the previous 6


tensor([12.])


In [15]:
# Correct way: zero out before each backward
w.grad.zero_()  # the underscore means "in-place operation"
loss = w ** 2
loss.backward()
print(w.grad)   # tensor([6.])  ✅ correct again

tensor([6.])
