In [2]:
import torch
import torch.nn as nn

#### Create a linear layer: 3 inputs → 2 outputs <br> Think: 3 features going in, 2 neurons coming out


In [3]:
layer = nn.Linear(in_features=3, out_features=2)

#### PyTorch automatically created weights and bias for us

In [4]:
print(layer.weight)   # shape: (2, 3) — 2 neurons, each with 3 weights
print(layer.bias)     # shape: (2,)   — one bias per neuron

Parameter containing:
tensor([[-0.5331, -0.3188, -0.0183],
        [-0.4886,  0.2525, -0.2198]], requires_grad=True)
Parameter containing:
tensor([-0.5014,  0.3731], requires_grad=True)


#### Pass one sample through (1 sample, 3 features)

In [5]:
x = torch.tensor([[1.0, 2.0, 3.0]])   # shape: (1, 3)
out = layer(x)
print(out)          # shape: (1, 2) — 1 sample, 2 outputs
print(out.shape)    # torch.Size([1, 2])

tensor([[-1.7268, -0.2701]], grad_fn=<AddmmBackward0>)
torch.Size([1, 2])


## Build your first real model with nn.Module

In [1]:
import torch
import torch.nn as nn

In [2]:
# Define the model as a class — this is the standard PyTorch pattern

class SimpleNet(nn.Module):

    def __init__(self):
        super().__init__()   # always call this first — sets up nn.Module internals

        # Define the layers (just declaring them, not running them yet)
        self.layer1 = nn.Linear(4, 8)   # 4 inputs → 8 neurons
        self.layer2 = nn.Linear(8, 1)   # 8 neurons → 1 output (e.g. regression)
        self.relu   = nn.ReLU()         # activation function (more on this below)

    def forward(self, x):
        # This defines how data flows through the network
        x = self.layer1(x)   # linear transform: (batch, 4) → (batch, 8)
        x = self.relu(x)     # apply activation: keeps shape (batch, 8)
        x = self.layer2(x)   # linear transform: (batch, 8) → (batch, 1)
        return x

In [3]:
# Create the model
model = SimpleNet()

In [4]:
# Pass a batch of 5 samples, each with 4 features
x = torch.rand(5, 4)       # shape: (5, 4)
output = model(x)          # calls forward() automatically
print(output.shape)        # torch.Size([5, 1])

torch.Size([5, 1])


In [6]:
# ReLU: max(0, x) — negative values become 0, positives pass through
relu = nn.ReLU()

x = torch.tensor([-3.0, -1.0, 0.0, 2.0, 5.0])
print(relu(x))   # tensor([0., 0., 0., 2., 5.])
#                          ↑ negatives killed  ↑ positives unchanged

tensor([0., 0., 0., 2., 5.])


In [7]:
model = SimpleNet()

# See all layers and their shapes
print(model)

SimpleNet(
  (layer1): Linear(in_features=4, out_features=8, bias=True)
  (layer2): Linear(in_features=8, out_features=1, bias=True)
  (relu): ReLU()
)


In [8]:
# Count total trainable parameters
total = sum(p.numel() for p in model.parameters())
print(f"Total parameters: {total}")
# Total parameters: 49
# (4×8 + 8 biases) + (8×1 + 1 bias) = 40 + 9 = 49

Total parameters: 49
